version: '2'

services:
    app:
        container_name: app
        build: .
        ports:
            - "80:3000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
        networks:
            - app-network
        links:
            - mongodb
        command: [ "nodemon", "-L", "src/index.js" ]

    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - app-network
        volumes:
            - ./dbdata:/data/db
        environment:
            MONGODB_USER: internetnation
            MONGODB_DATABASE: internetnation
            MONGODB_PASS: int423erne581tnat30591on

networks:
    app-network:
        driver: bridge